//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR2K3Results_MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public long Id { get; set; }
        public string SeriesName { get; set; }
        public string SeriesShort { get; set; }
        public string RosterFile { get; set; }
        public string SeriesLogo { get; set; }
        public string SancLogo { get; set; }
        public string NR2K3Dir { get; set; }
    }
}
